name: Deploy para Desenvolvimento (InfinityFree)

on:
  workflow_run:
    # 1. Escuta por execuções do workflow com este nome exato:
    workflows: ["Auto merge no branch desenvolvimento"]
    # 2. Apenas quando a execução for concluída:
    types:
      - completed
    # 3. A CONDIÇÃO DA BRANCH FOI REMOVIDA DAQUI

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    # A CONDIÇÃO DE SUCESSO AINDA GARANTE A SEGURANÇA
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # Esta linha garante que pegamos o código da branch 'desenvolvimento'
          # após o merge feito pelo workflow anterior.
          ref: ${{ github.event.workflow_run.head_branch }}

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/bio-ubs-desenvolvimento/