name: Deploy para Desenvolvimento (InfinityFree)

on:
  # O NOVO GATILHO:
  workflow_run:
    # 1. Escuta por execuções do workflow com este nome exato:
    workflows: ["Auto merge no branch desenvolvimento"]
    # 2. Apenas quando a execução for concluída:
    types:
      - completed
    # 3. E apenas se a execução aconteceu na branch 'desenvolvimento':
    branches:
      - desenvolvimento

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    # 4. CONDIÇÃO DE SEGURANÇA: Só executa se o workflow anterior teve SUCESSO.
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    # 5. AJUSTE NO CHECKOUT: Pega o código exato do commit que o workflow anterior usou.
    - name: Checkout
      uses: actions/checkout@v4
      with:
        ref: ${{ github.event.workflow_run.head_sha }}

    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        server-dir: /htdocs/bio-ubs-desenvolvimento/