name: Deploy para Desenvolvimento (InfinityFree)

on:
  workflow_run:
    workflows: ["Auto merge no branch desenvolvimento"]
    types:
      - completed

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'desenvolvimento'
    steps:
      - name: Checkout da branch desenvolvimento
        uses: actions/checkout@v4
        with:
          # Fazemos o checkout da branch desenvolvimento, que foi atualizada pelo workflow anterior
          ref: 'desenvolvimento'

      - name: FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: /htdocs/bio-ubs-desenvolvimento/